language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
repo: paulfliu/paulfliu.github.io
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: 43245fa9ed3c7029eb16d5f517d7546e26667fd1
  keep-history: true
  on:
    branch: master
